<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Chronomail Webmail Archive plugin             |
 |                                                                       |
 | Copyright (C) The Chronomail Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/chronomail-webmail/resource/plugin-archive/
*/

$labels['buttontext'] = 'ارشیو';
$labels['buttontitle'] = 'ارشیو این پیام';
$labels['archived'] = 'با موفقیت ارشیو شد';
$labels['archivefolder'] = 'ارشیو';
$labels['settingstitle'] = 'ارشیو';
$labels['archivetypefolder'] = 'پوشه اصلی';
$labels['archivetypesender'] = 'ایمیل فرستنده';
$labels['unkownsender'] = 'نا شناس';
?>
