<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Chronomail Webmail Managesieve plugin         |
 |                                                                       |
 | Copyright (C) The Chronomail Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/chronomail-webmail/resource/plugin-managesieve/
*/


$labels['messagedelete'] = 'रद्द करें';
$labels['del'] = 'मिटा';
$labels['notifymethodmailto'] = 'मेल';
$labels['datetest'] = 'तारीख';
$labels['vacation.subject'] = 'विशय';
