<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Chronomail Webmail Managesieve plugin         |
 |                                                                       |
 | Copyright (C) The Chronomail Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/chronomail-webmail/resource/plugin-managesieve/
*/


$labels['del'] = 'سڕینەوە';
$labels['notifymethodtel'] = 'تەلەفۆن';
$labels['datetest'] = 'بەروار';
$labels['vacation.subject'] = 'ناونیشان';
