<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Chronomail Webmail Managesieve plugin         |
 |                                                                       |
 | Copyright (C) The Chronomail Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/chronomail-webmail/resource/plugin-managesieve/
*/


$labels['sender'] = 'بھیجنے والا';
$labels['flagdeleted'] = 'ختم ہو گیا';
$labels['datetest'] = 'تاریخ';
$labels['vacation.subject'] = 'مضمون';
