<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Chronomail Webmail Help plugin                |
 |                                                                       |
 | Copyright (C) The Chronomail Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/chronomail-webmail/resource/plugin-help/
*/

$labels['help'] = 'Pomoč';
$labels['about'] = 'Vizitka';
$labels['license'] = 'Licenca';
$labels['csrfinfo'] = 'Preberite več o CSRF in kako ste zaščiteni';
?>
