<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Chronomail Webmail Vcard Attachments plugin   |
 |                                                                       |
 | Copyright (C) The Chronomail Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/chronomail-webmail/resource/plugin-vcard_attachments/
*/

$labels['addvcardmsg'] = 'Добавить в контакты';
$labels['vcardsavefailed'] = 'Не удалось сохранить vCard';
$labels['attachvcard'] = 'Вложить vCard';
$labels['vcardattached'] = 'Вложенный vCard';
$labels['vcard'] = 'vCard';
$labels['forwardvcard'] = 'Переслать vCard';
