<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Chronomail Webmail Vcard Attachments plugin   |
 |                                                                       |
 | Copyright (C) The Chronomail Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/chronomail-webmail/resource/plugin-vcard_attachments/
*/

$labels['addvcardmsg'] = 'Pridať vizitku vCard do adresára';
$labels['vcardsavefailed'] = 'Vizitku vCard nemožno uložiť';
$labels['attachvcard'] = 'Pripojiť vizitku vCard';
$labels['vcardattached'] = 'Súbor vCard bol pripojený.';
$labels['vcard'] = 'Vizitka vCard';
$labels['forwardvcard'] = 'Preposlať vCard';
