<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Chronomail Webmail Archive plugin             |
 | Copyright (C) The Chronomail Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/chronomail-webmail/resource/plugin-attachment_reminder/
*/

$messages['missingattachment'] = "האם חסרה צרופה?";
$messages['forgotattachment'] = "האם שכחת לצרף קובץ?";
$messages['reminderoption'] = "להזכיר לצרף נספח";
$messages['keywords'] = "נספח,קובץ,לצרף,מצורף,מצרף,מצרפת,רצ\"ב,קו\"ח,קורות חיים";
