<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Chronomail Webmail Archive plugin             |
 | Copyright (C) The Chronomail Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/chronomail-webmail/resource/plugin-attachment_reminder/
*/

$messages['missingattachment'] = "Vantar viðhengi?";
$messages['forgotattachment'] = "Gleymdirðu að hengja við skrá?";
$messages['reminderoption'] = "Minna á viðhengi sem gleymast";
$messages['keywords'] = "viðhengi,skrá,hengja við,innfellt,CV,meðfylgjandi,ferilskrá,mynd";
