<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Chronomail Webmail New User Dialog plugin     |
 |                                                                       |
 | Copyright (C) The Chronomail Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/chronomail-webmail/resource/plugin-new_user_dialog/
*/

$labels['identitydialogtitle'] = 'Bizskrivit hoc\'h anv kaser mar plij';
$labels['identitydialoghint'] = 'Diskouezet eo ar boest e-pad ar c\'hentañ kennask.';
