<?php

/*
 +-----------------------------------------------------------------------+
 | localization//labels.inc                                         |
 |                                                                       |
 | Language file of the chronomail Webmail client                         |
 | Copyright (C) 2012, The chronomail Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Madghis <mbuzakhar@armas.ly>                                  |
 +-----------------------------------------------------------------------+
*/

$labels['username'] = 'Izwel n';

