<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Chronomail Webmail Zipdownload plugin         |
 |                                                                       |
 | Copyright (C) The Chronomail Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/chronomail-webmail/resource/plugin-zipdownload/
*/

$labels['downloadall'] = 'Pellgargañ an holl stagadennoù';
$labels['download'] = 'Pellgargañ…';
$labels['downloadmbox'] = 'Mentrezh Mbox (.zip)';
$labels['downloadmaildir'] = 'Mentrezh Maildir (.zip)';
$labels['downloademl'] = 'Tarzh (.eml)';
