<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Chronomail Webmail Zipdownload plugin         |
 |                                                                       |
 | Copyright (C) The Chronomail Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/chronomail-webmail/resource/plugin-zipdownload/
*/

$labels['downloadall'] = 'Λήψη όλων των συνημμένων';
$labels['download'] = 'Λήψη...';
$labels['downloadmbox'] = 'Μορφή mbox (.zip)';
$labels['downloadmaildir'] = 'Μορφή maildir (.zip)';
$labels['downloademl'] = 'Πηγή (.eml)';
$labels['sizelimiterror'] = 'Το συνολικό μέγαθος των επιλεγμένων μηνυμάτων υπερβαίνει το όριο ($size)';
