<?php

/**
 +-----------------------------------------------------------------------+
 | Localization file of the Chronomail Webmail Enigma plugin              |
 |                                                                       |
 | Copyright (C) The Chronomail Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/chronomail/chronomail-webmail/plugin-enigma/
*/

$labels['keyname'] = 'Ad';
$labels['keyid'] = 'Açar ID';
$labels['typeencrypt'] = 'Şifrələ';
$labels['subkeycreated'] = 'Yaradılma tarixi';
$labels['expiresnever'] = 'heç vaxt';
$labels['unknown'] = 'naməlum';
$labels['newkeypass'] = 'Şifrə';
?>
