<?php

/**
 +-----------------------------------------------------------------------+
 | Localization file of the Chronomail Webmail Enigma plugin              |
 |                                                                       |
 | Copyright (C) The Chronomail Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/chronomail/chronomail-webmail/plugin-enigma/
*/

$labels['keyname'] = 'Naam';
$labels['subkeycreated'] = 'Aangemaakt';
$labels['expiresnever'] = 'nooit';
$labels['unknown'] = 'onbekend';
$labels['keychpass'] = 'Wijzig wachtwoord';
$labels['newkeypass'] = 'Wachtwoord';
?>
