<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Chronomail Webmail Hide-Blockquote plugin     |
 |                                                                       |
 | Copyright (C) The Chronomail Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/chronomail-webmail/resource/plugin-hide_blockquote/
*/

$labels['hide'] = 'Dölj';
$labels['show'] = 'Visa';
$labels['quotelimit'] = 'Dölj citat när antalet rader överstiger';
