<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Chronomail Webmail Emoticons plugin           |
 |                                                                       |
 | Copyright (C) The Chronomail Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/chronomail-webmail/resource/plugin-emoticons/
*/

$labels['emoticonsdisplay'] = 'Matnli xabarlarda smayliklar tasvirlansinmi?';
$labels['emoticonscompose'] = 'Smayliklarni faollashtirish';
?>
